#  1.Readthe dataset into python environment

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_set=pd.read_excel(r'C:\Users\user\Downloads\iris.xls')
data_set.head()                  

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [3]:
data_set.info()#to check for missing values 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
data_set.isna().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [5]:
col=['SL','SW','PL']#Filling the missing values with median
for i in col:
    data_set[i]=data_set[i].fillna(data_set[i].median())

In [6]:
data_set.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [7]:
data_set.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  5.8  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [8]:
data_set['SL'].unique()

array([5.1, 4.9, 5.8, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.7, 5.2, 4.7, 5.5,
       4.5, 5.3, 7. , 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7, 6.2,
       6.4, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [9]:
data_set['SW'].unique()

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 4. , 4.4, 3.8, 3.7, 3.3,
       4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

In [10]:
data_set['PL'].unique()

array([1.4 , 1.3 , 1.5 , 1.7 , 1.6 , 1.1 , 1.2 , 1.  , 1.9 , 4.35, 4.7 ,
       4.5 , 4.9 , 4.  , 4.6 , 3.3 , 3.9 , 3.5 , 4.2 , 3.6 , 4.4 , 4.1 ,
       4.8 , 4.3 , 5.  , 3.8 , 3.7 , 5.1 , 3.  , 6.  , 5.9 , 5.6 , 5.8 ,
       6.6 , 6.3 , 5.3 , 5.5 , 6.7 , 6.9 , 5.7 , 6.1 , 6.4 , 5.4 , 5.2 ])

In [11]:
data_set['PW'].unique()

array([0.2, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, 1.6, 1. , 1.1, 1.8,
       1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2. , 2.4, 2.3])

# Min Max scaling

In [13]:
X1=data_set.drop(['Classification'],axis=1)
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
X1=min_max.fit_transform(X1)

X1=pd.DataFrame(X1,columns=['SL','SW','PL','PW'])

In [14]:
X1.describe()

SL          SW          PL          PW
count  150.000000  150.000000  150.000000  150.000000
mean     0.431481    0.436389    0.471186    0.457778
std      0.224602    0.175831    0.293123    0.317984
min      0.000000    0.000000    0.000000    0.000000
25%      0.250000    0.333333    0.101695    0.083333
50%      0.416667    0.416667    0.567797    0.500000
75%      0.583333    0.531250    0.694915    0.708333
max      1.000000    1.000000    1.000000    1.000000

In [15]:
Y1=data_set['Classification']#Y1 contains the target


# Support Vector Machine 

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [17]:
#split the data into test and training
X_train,X_test,Y_train,Y_test=train_test_split(X1,Y1,test_size=0.2,random_state= 42)

In [18]:
#create and train classification model
classifier=SVC()
classifier.fit(X_train,Y_train)

SVC()

In [19]:
#make prediction on test set
Y_pred=classifier.predict(X_test)

In [20]:
#Evaluating model performance
accuracy=accuracy_score(Y_test,Y_pred)
print('Accuracy:',accuracy)

Accuracy: 0.9666666666666667


# Using Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,Y_train)
Y_prediction=model.predict(X_test)
accuracy1=accuracy_score(Y_test,Y_prediction)
print('AccuracyLR:',accuracy1)

AccuracyLR: 0.9666666666666667


# Using Random Forest

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
#creating random forest classifier
clf=RandomForestClassifier(n_estimators=100,random_state=42)
clf.fit(X_train,Y_train)
y_predict=clf.predict(X_test)
accuracy2=accuracy_score(Y_test,y_predict)
print('Accuracy2:',accuracy2)


Accuracy2: 1.0


# From the Three models used the best method is thr Random Forest Method where the accuracy is one